[package]
name = "sazen-tea-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
lettre = "0.11.15"
log = "0.4.27"
reqwest = "0.12.15"
select = "0.6.1"
tokio = { version = "1.44.1", features = ["full"] }
